### Get podcast list

GET http://localhost:3000/api/podcast-list

### Get podcast details
GET http://localhost:3000/api/podcast/asp66-google-znovu-vchyt-nas-arkhitekturi


### Get podcast

GET https://feeds.acast.com/public/shows/android-story

### Test api

GET http://localhost:3002/api/test
