### Get podcast list

GET http://localhost:3000/api/podcast-list

### Get podcast details
GET http://localhost:3000/api/podcast/asp66-google-znovu-vchyt-nas-arkhitekturi


### Get podcast
GET https://feeds.acast.com/public/shows/android-story

### Get images
GET http://localhost:3000/api/images/logo.jpg

### Test get image
GET https://story-podcast.ams3.cdn.digitaloceanspaces.com/logo.jpg

### Generetae rss
POST http://localhost:3000/api/rss

